// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting_Module.Models
{
    public partial class AC_GetCashNBankBookDataResult
    {
        public DateTime? VoucherDate { get; set; }
        [StringLength(20)]
        public string VoucherNumber { get; set; }
        public int? AccountID { get; set; }
        [StringLength(50)]
        public string AccountName { get; set; }
        public long? AccountCode { get; set; }
        [StringLength(2147483647)]
        public string Description { get; set; }
        [Column("CreditAmount", TypeName = "money")]
        public decimal CreditAmount { get; set; }
        [Column("DebitAmount", TypeName = "money")]
        public decimal DebitAmount { get; set; }
        [StringLength(20)]
        public string ChequeNo { get; set; }
        public DateTime? ChequeDate { get; set; }
        [Column("Balance", TypeName = "decimal(2,2)")]
        public decimal Balance { get; set; }
        [StringLength(1)]
        public string BalanceType { get; set; }
    }
}
