// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting_Module.Models
{
    public partial class ACC_Rpt_ReceivePaymentsResult
    {
        public int? AccountID { get; set; }
        public long? AccountCode { get; set; }
        [StringLength(20)]
        public string OpeningOrClosing { get; set; }
        [StringLength(50)]
        public string AccountName { get; set; }
        [StringLength(20)]
        public string GroupType { get; set; }
        [Column("Cash", TypeName = "decimal(18,0)")]
        public decimal Cash { get; set; }
        [Column("Bnk_120201", TypeName = "decimal(18,0)")]
        public decimal Bnk_120201 { get; set; }
        [Column("Bnk_120202", TypeName = "decimal(18,0)")]
        public decimal Bnk_120202 { get; set; }
        [Column("Bnk_120203", TypeName = "decimal(18,0)")]
        public decimal Bnk_120203 { get; set; }
        [Column("Bnk_120204", TypeName = "decimal(18,0)")]
        public decimal Bnk_120204 { get; set; }
        [Column("Bnk_120205", TypeName = "decimal(18,0)")]
        public decimal Bnk_120205 { get; set; }
        [Column("Bnk_120206", TypeName = "decimal(18,0)")]
        public decimal Bnk_120206 { get; set; }
        [Column("Bnk_120207", TypeName = "decimal(18,0)")]
        public decimal Bnk_120207 { get; set; }
        [Column("Bnk_120208", TypeName = "decimal(18,0)")]
        public decimal Bnk_120208 { get; set; }
        [Column("Bnk_120209", TypeName = "decimal(18,0)")]
        public decimal Bnk_120209 { get; set; }
        [Column("Bnk_120210", TypeName = "decimal(18,0)")]
        public decimal Bnk_120210 { get; set; }
        [Column("Bnk_120211", TypeName = "decimal(18,0)")]
        public decimal Bnk_120211 { get; set; }
        [Column("Bnk_120212", TypeName = "decimal(18,0)")]
        public decimal Bnk_120212 { get; set; }
        [Column("Bnk_120213", TypeName = "decimal(18,0)")]
        public decimal Bnk_120213 { get; set; }
        [Column("Bnk_120214", TypeName = "decimal(18,0)")]
        public decimal Bnk_120214 { get; set; }
    }
}
