// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting_Module.Models
{
    public partial class ACC_GET_AccountTreeByCodeResult
    {
        [StringLength(156)]
        public string LocatedPath { get; set; }
        [StringLength(50)]
        public string MasterName { get; set; }
        public string IsMaster { get; set; }
        public string IsParent { get; set; }
        public long? ParentCode { get; set; }
        [StringLength(50)]
        public string Child1Name { get; set; }
        public long? Ch1Code { get; set; }
        [StringLength(50)]
        public string Child2Name { get; set; }
        public long? Ch2Code { get; set; }
        [StringLength(50)]
        public string Child3Name { get; set; }
        public long? Ch3Code { get; set; }
    }
}
