// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccAccount
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public long? AccountCode { get; set; }

    public string IsMaster { get; set; }

    public string IsParent { get; set; }

    public int? Label { get; set; }

    public decimal? OpeningBalance { get; set; }

    public int? ParentId { get; set; }

    public string Status { get; set; }

    public int? CompanyId { get; set; }

    public int CreateUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? EditUserId { get; set; }

    public DateTime? EditDate { get; set; }
}