// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accounting_Module.Models;

public partial class AccAccount

{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AccountID { get; set; }

    public string AccountName { get; set; }

    public long? AccountCode { get; set; }

    public string IsMaster { get; set; }

    public string IsParent { get; set; }

    public int? Label { get; set; }

    public decimal? OpeningBalance { get; set; }

    public int? ParentID { get; set; }

    public string Status { get; set; }

    public int? CompanyId { get; set; }

    public int CreateUserId { get; set; }

    public DateTime CreateDate { get; set; }= DateTime.Now;

    public int? EditUserId { get; set; }

    public DateTime? EditDate { get; set; } = DateTime.Now;
}