// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccCostCenter
{
    public int CostCenterId { get; set; }

    public string CostCenterName { get; set; }

    public string CostCenterShortName { get; set; }

    public int? CompanyId { get; set; }

    public string Status { get; set; }

    public int CreateUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? EditUserId { get; set; }

    public DateTime? EditDate { get; set; }
}