// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccFy
{
    public int Fyid { get; set; }

    public string Fyname { get; set; }

    public string FyshortCode { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }
}