// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccRptTblReceivePayment
{
    public int RowId { get; set; }

    public int? AccountId { get; set; }

    public string GroupType { get; set; }

    public string OpeningOrClosing { get; set; }

    public decimal? Cash { get; set; }

    public decimal? Bnk120201 { get; set; }

    public decimal? Bnk120202 { get; set; }

    public decimal? Bnk120203 { get; set; }

    public decimal? Bnk120204 { get; set; }

    public decimal? Bnk120205 { get; set; }

    public decimal? Bnk120206 { get; set; }

    public decimal? Bnk120207 { get; set; }

    public decimal? Bnk120208 { get; set; }

    public decimal? Bnk120209 { get; set; }

    public decimal? Bnk120210 { get; set; }

    public decimal? Bnk120211 { get; set; }

    public decimal? Bnk120212 { get; set; }

    public decimal? Bnk120213 { get; set; }

    public decimal? Bnk120214 { get; set; }

    public string CreateUserId { get; set; }
}