// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccTempVoucher
{
    public int TempId { get; set; }

    public int? AccountId { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public string Narration { get; set; }

    public int? CreateUserId { get; set; }
}