// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccVoucher
{
    public long VoucherAutoId { get; set; }

    public int? CostCenterId { get; set; }

    public string VoucherNumber { get; set; }

    public DateTime? VoucherDate { get; set; }

    public int? AccountId { get; set; }

    public string PaymentMode { get; set; }

    public string ReceiveChequeNo { get; set; }

    public DateTime? ReceiveChequeDate { get; set; }

    public decimal? DebitAmount { get; set; }

    public decimal? CreditAmount { get; set; }

    public string Description { get; set; }

    public string BankId { get; set; }

    public string BankAccountName { get; set; }

    public string ChequeNo { get; set; }

    public DateTime? ChequeDate { get; set; }

    public string Cash { get; set; }

    public string IsOpening { get; set; }

    public string RefNo { get; set; }

    public string PostedFrom { get; set; }

    public string Module { get; set; }

    public string UserId { get; set; }

    public string Status { get; set; }

    public int? CompanyId { get; set; }

    public int CreateUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public int? EditUserId { get; set; }

    public DateTime? EditDate { get; set; }
}