// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Module.Models;

public partial class AccVoucherType
{
    public int VoucherTypeId { get; set; }

    public string VoucherTypeName { get; set; }

    public string ShortCode { get; set; }
}