// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Accounting_Module.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Accounting_Module.Models
{
    public partial interface IAccountsDBContextProcedures
    {
        Task<List<AC_GetCashNBankBookDataResult>> AC_GetCashNBankBookDataAsync(int? accountID, DateTime? fromDate, DateTime? toDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AC_GetOpeningBalanceAsync(string voucherTable, string accountID, string tillDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AC_GetTrialBalanceAsync(string accTable, string voucherTable, string fromDate, string toDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_Create_AccountAsync(string accTableName, string accountName, string accountCode, string isMaster, string isParent, string label, string openingBalance, string parentID, string status, string companyID, string createUserID, string createDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_Create_VoucherAsync(string accTableName, string costCenterID, string voucherNumber, string voucherDate, string accountID, string paymentMode, string receiveChequeNo, string receiveChequeDate, string debitAmount, string creditAmount, string description, string bankID, string bankAccountName, string chequeNo, string chequeDate, string cash, string isOpening, string refNo, string postedFrom, string module, string userID, string status, string companyID, string createUserID, string createDate, string approvedBy, string approvedDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_Edit_AccountAsync(string accTableName, string accountID, string accountName, string accountCode, string isMaster, string isParent, string label, string openingBalance, string parentID, string status, string companyID, string editUserID, string editDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_Edit_VoucherAsync(string accTableName, string voucherAutoID, string accountID, string debitAmount, string creditAmount, string description, string chequeNo, string chequeDate, string editDate, string editUserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GenerateAccountCodeAsync(string tableName, string parentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ACC_GenerateBalanceSheetResult>> ACC_GenerateBalanceSheetAsync(string dateFrom, string dateTo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GenerateVoucherIDAsync(string tableName, string type, string prefix, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GET_AccountLocationAsync(string accTableName, string accountID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GET_AccountTreeAsync(string tableName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ACC_GET_AccountTreeByCodeResult>> ACC_GET_AccountTreeByCodeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetAccountListAsync(string tableName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetAccountScheduleReportAsync(string accTable, string voucherTable, string startDate, string endDate, string parentCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ACC_GetBalanceSheetLevelWiseDataResult>> ACC_GetBalanceSheetLevelWiseDataAsync(string dateFrom, string dateTo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetIncomeStatementAsync(string accTable, string voucherTable, string startDate, string endDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetSubsidiaryLedgerDataAsync(string accTable, string voucherTable, string accountID, string fromDate, string toDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetTempVoucherListAsync(string accTableName, string createUserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetUsableAccountListAsync(string tableName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetVoucherByIDAsync(string accTable, string voucherTable, string voucherNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetVoucherDetailsAsync(string accTable, string voucherTable, string startDate, string endDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ACC_GetVoucherInfoListAsync(string accTable, string voucherTable, string startDate, string endDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ACC_Rpt_ReceivePaymentsResult>> ACC_Rpt_ReceivePaymentsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ACC_Rpt_ReceivePayments_InsertResult>> ACC_Rpt_ReceivePayments_InsertAsync(string colName, int? accountID, decimal? amount, string groupType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
